CREATE DATABASE n0blog_dev;
CREATE DATABASE n0blog_test;
CREATE DATABASE n0blog;
GRANT ALL PRIVILEGES ON DATABASE n0blog_dev TO n0blog;
GRANT ALL PRIVILEGES ON DATABASE n0blog_test TO n0blog;
GRANT ALL PRIVILEGES ON DATABASE n0blog TO n0blog;
